# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
      
jobs:
  bro:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo you ok?

workflows:
  my-custom-workflow:
    jobs:
      - bro








